---
- name: 'Clone pytorch repo'
  ansible.builtin.git:
    repo: 'git@github.com:pytorch/pytorch.git'
    dest: '~/pytorch'
  tags:
    - pytorch

- name: 'Create conda environment'
  shell: 'source /etc/profile && conda create -y --name build-pytorch'
  args:
     executable: /bin/bash
  tags:
    - pytorch

- name: 'Activate conda environment'
  shell: 'source /etc/profile && conda activate build-pytorch'
  args:
     executable: /bin/bash
  tags:
    - pytorch

- name: 'Install mkl'
  shell: 'source /etc/profile && conda install mkl mkl-include'
  args:
     executable: /bin/bash
  tags:
    - pytorch

- name: 'Install cuda'
  shell: 'source /etc/profile && conda install -c pytorch magma-cuda110'
  args:
     executable: /bin/bash
  tags:
    - pytorch
