---
- name: 'Clone pytorch repo'
  ansible.builtin.git:
    repo: 'git@github.com:pytorch/pytorch.git'
    dest: '~/pytorch'
  tags:
    - pytorch

- name: 'Create conda environment'
  shell: 'source /etc/profile && conda create -y --name build-pytorch'
  args:
     executable: /bin/bash
  tags:
    - pytorch

- name: 'Install pytorch'
  shell: >
    cd ~/pytorch && 
    source /etc/profile &&
    conda init bash &&
    conda activate build-pytorch && 
    conda install cmake ninja && 
    pip install -r requirements.txt && 
    conda install mkl mkl-include &&
    conda install -c pytorch magma-cuda110 &&
    make triton
  args:
     executable: /bin/bash
  tags:
    - pytorch
