---
- name: 'Clone pytorch repo'
  ansible.builtin.git:
    repo: 'git@github.com:pytorch/pytorch.git'
    dest: '~/pytorch'
  tags:
    - pytorch
    - pytorch-clone

- name: 'Create conda environment'
  shell: 'conda create -y --name build-pytorch'
  args:
     executable: /bin/bash
  tags:
    - pytorch
    - pytorch-create-env

- name: 'init conda'
  shell: 'conda init bash'
  args:
     executable: /bin/bash
  tags:
    - pytorch

- name: 'Install pytorch'
  shell: >
    cd ~/pytorch && 
    conda install cmake ninja && 
    pip install -r requirements.txt && 
    conda install mkl mkl-include &&
    conda install -c pytorch magma-cuda110 &&
    make triton &&
    export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"} &&
    python setup.py develop
  args:
     executable: /bin/bash
  tags:
    - pytorch
    - pytorch-install
